fun Void main()
	x = try
		do
			assert false
			"unreachable"
		catch Exception e
			e.description()
	assert x == "Assertion failed."
